### PR TITLE
Universal Studios Singapore Wait Times

### PR DESCRIPTION
**Pull request by rambleraptor**
This should add in wait times for Universal Studios Singapore. My Javascript knowledge is pretty basic, so let me know if there's any style fixes you would like.

### CODE REVIEW

**Comment by cubehouse** [comment]
Sorry I've not looked at this in detail yet, I'm pretty busy with boring actual real life things for the next day or two.

Out of curiosity, can we get the park opening times too?

**Comment by rambleraptor** [comment]
No worries! I can look into it. The API endpoint in the issue didn't have them included, so I'll poke around for them. Might take me a couple days.

**Comment by cubehouse** [comment]
Doesn't look like they have any sort of mobile phone app for the park? So this might be the only source available for times, where we'll have to parse through the HTML manually (yuck, but sometimes needs to be done...)
http://www.rwsentosa.com/language/en-US/Homepage/Attractions/UniversalStudiosSingapore

Might get some time tonight (UK time) to have a poke.

**Comment by rambleraptor** [comment]
It's the RWS (Resorts World Sentosa) app. That's the app that consumes the API.

**Comment by cubehouse** [comment]
Looks like this might an iPhone-only app? If you have a link to an Android version, let me know :)

**Comment by cubehouse** [comment]
Looks like you've missed adding the xml2js dependency to get this working. When installing new libraries, if you're using npm make sure you use `--save` to also write the dependency to the package.json file :)

I had a little play with the code here: https://github.com/cubehouse/themeparks/tree/rambleraptor-master

Works great though 👍  Once one of us gets a chance to figure out the opening times, we'll get this merged in!

**Comment by rambleraptor** [comment]
Thanks a lot for making those changes! I deleted xml2js because I didn't specify for it to run anywhere. Javascript can be a bit quirky at times. Thanks for the style fixes!

I glanced through the Resorts World Sentosa app and there's a couple API endpoints that expose the opening times. None of them are particularly friendly though.

### Option 1
http://cma.rwsentosa.com/Service.svc/GetDirectoryByCategoryID?CategoryID=3&languageID=1

This is the directory of all the attractions in RW Sentosa, including Universal Singapore. The opening hours are listed under <OpeningHour /> in a big block of text. I don't have any guarantee what that block of text will look like. Right now, it says "Mon - Sat 10am-7pm ..."

### Option 2
http://cma.rwsentosa.com/Service.svc/GetZoneDirectoriesByDirectoryCategoryID?DirectoryCategoryID=5&LanguageID=1&Latitude=0.0&Longitude=0.0&USS=true 

This is the list of restaurants at Universal Singapore. Most all of them have hours. By going through each one and grabbing the earliest opening time / latest closing time, you can get the full park hours (in theory). The values are much easier to parse (consistent format), but you may not get the correct answer.

**Comment by cubehouse** [comment]
The xml2js is a weird one, our HTTP library (needle) just additionally uses it if it finds it installed and detects an XML file has been downloaded. Because XML is kind of rare, they don't include xml2js by default to keep their dependencies small.

Those links look great, I'll have a look and ponder the best approach. This is one of the stranger theme park APIs I've seen, it feels ancient! I've often had to fallback to some flexible text parsing, it's amazing how many parks have human-entered text for their opening times.

Thank you for figuring the URLs out :)

**Comment by cubehouse** [comment]
Looking at their official site, the times returned in the text block in the XML aren't even correct, so I think I'm going to parse this page manually to get the best results: http://www.rwsentosa.com/Homepage/Attractions/UniversalStudiosSingapore

**Comment by rambleraptor** [comment]
Blech! What a mess.

**Comment by cubehouse** [comment]
Knocked up a parser for opening hours, seems to work.

3acf68dfc1b6e0

Wait times appear to be mostly returning 5 minutes even though the park is closed? Will have to monitor when the park is actually open, then we'll get this merged in!

**Comment by cubehouse** [comment]
Merging in now! Will be rolled out in 4.6.0 later today.

**Comment by rambleraptor** [comment]
That's awesome! Thanks for everything! The library is absolutely awesome.

**Pull request merged**
