### PR TITLE
Add Toverland

### PR DESCRIPTION
**Pull request by tpxtron**
#321

### CODE REVIEW

**Comment by tpxtron** [comment]
...not sure why the Travis build with Node.js:stable fails. 🤔

**Comment by cubehouse** [comment]
Don't worry about the travis build, everything else has passed, including 14.x which is the current LTS Node. I think one of the dependencies doesn't compile properly on Travis at the moment. We're using the GitHub CI now anyway.

**Comment by timyboy12345** [comment]
This may be a bit of a noob question, but how do retrieve these URLs? I saw that Toverland also lists amenities like toilets, shops and restaurants in their app, but I wasn't able to guess all those URL's.

I would like to contribute to this PR, but have no idea how these URLs are retrieved. I did manage to guess the URL for shops (`https://api.toverland.com/v1/park/shop/operationInfo/list`) and shows (`https://api.toverland.com/v1/park/show/operationInfo/list`, but there are no shows at the moment)

**Comment by AlexVV13** [comment]
> This may be a bit of a noob question, but how do retrieve these URLs? I saw that Toverland also lists amenities like toilets, shops and restaurants in their app, but I wasn't able to guess all those URL's.
> 
> I would like to contribute to this PR, but have no idea how these URLs are retrieved. I did manage to guess the URL for shops (`https://api.toverland.com/v1/park/shop/operationInfo/list`) and shows (`https://api.toverland.com/v1/park/show/operationInfo/list`, but there are no shows at the moment)

You could take a look at the code, or at this comment placed on an issue here ‘Add Toverland’.
I guess that’ll explain your question about this.
https://github.com/cubehouse/themeparks/issues/321#issuecomment-717414740

**Pull request merged**
