### PR TITLE
Added liseberg park

### PR DESCRIPTION
**Pull request by hemi1986**
I added the liseberg api.

The liseberg api sometimes is a little strange (you can get the waittime at different endpoints (interactive map api and a queue api for example or they return a "from to"-value for their waittimes)... i now use the "maps api" which they use for their interactive map on their website as well because it features all information on the rides we will need.

Let me know if i should improve something

### CODE REVIEW

**Comment by cubehouse** [comment]
Thank you for this PR, it looks great :)

I'm running the class with:
```
NODE_DEBUG=themeparks PARKID=Liseberg PRINTDATA=true npm run testonline
```
and seeing a huge amount of HTTP calls. I haven't looked into how the app behaves, but can this be slimmed down? Or at least can we make use of the Cache library to not need to fetch it all every time we do an update?

There are a lot of date errors too, like "Invalid scheduleData.closingTime".

Also, if the rides ever support FastPass, please override the FastPass getter for the park class so it can be queried:
```
get FastPass() {
    return true;
}
```

Thanks!

**Comment by hemi1986** [comment]
Hey,

Thanks for your hints :) I had some errors in the code why those date errors appeared. Should be fixed now.

I overwrote the fastpass getter as you said and added caching to the season and rideoverview calls. Additionally i also found a problem in that code as well why some rides where queried multiple times at one Waittime call. The api calls should now be slimmed down.

One thing: I wrote you a private email because of this PR. I dont know how important the topic in that email is but can you please be so kind and check this private email?

**Comment by cubehouse** [comment]
Sorry I've been a bit AWOL. I'm afraid I don't think I ever got an email from you!

**Comment by cubehouse** [comment]
Thank you for this. I'm happy with this and will publish shortly.

**Pull request merged**
