### PR TITLE
fix: #144 FetchFacilitiesURL for DisneylandParis

### PR DESCRIPTION
**Pull request by midiland**
#144 Fix this issue but probably more test requires because I only use GetWaitTimes on this park

### CODE REVIEW

**Comment by LouisForaux** [comment]
Everything Works for me with the changes !

Thanks !

**Comment by VitalyChe** [comment]
@midiland Cool, it works perfectly, thank you very much!

**Comment by cubehouse** [comment]
Thanks guys! Published in 4.7.13

**Comment by VitalyChe** [comment]
@cubehouse Thank you for the great project!

**Pull request merged**
