### PR TITLE
Add facilityCode to TDR wait time meta property

### PR DESCRIPTION
**Pull request by rorpage**
Addresses #244

### CODE REVIEW

**Comment by rorpage** [comment]
Sorry for all of the noise. I accidentally committed a Visual Studio file and then squashed my history to get rid of it.

**Comment by cubehouse** [comment]
Thank you for this!

Instead of overriding the UpdateRide function, can you add a meta object to the rideData object in FetchWaitTimes?

```
const rideData = {
    // ride name
    name: rides[ride.id].name,
    meta: {
        facilityCode: rides[ride.id].facilityCode,
    },
};
```

**Comment by rorpage** [comment]
@cubehouse I have addressed your feedback!

**Comment by cubehouse** [comment]
Brilliant thank you! If you can make the linter happy with some trailing commas then I will merge this in.

You can test the linter "npm run lint" if your IDE doesn't pick up on the linter rules automatically.

**Comment by rorpage** [comment]
@cubehouse :boom: there we go

**Comment by cubehouse** [comment]
Thank you, pushed in 5.1.24

**Pull request merged**
