### PR TITLE
Fixes cubehouse/themeparks#206

### PR DESCRIPTION
**Pull request by jeanmatthieud**
+ Code simplified with the use of cheerio lib

### CODE REVIEW

**Comment by jeanmatthieud** [comment]
Could you re-run Travis ?
The error is due to a network failure during the build.
I don't know if the build passes with the last commit.

**Comment by cubehouse** [comment]
Heya, I ran it again and it's failing the linter still I'm afraid :)

**Comment by jeanmatthieud** [comment]
I will check that on Monday ;)

Le ven. 19 juil. 2019 à 21:05, Jamie Holding <notifications@github.com> a
écrit :

**Comment by jeanmatthieud** [comment]
Finally fixed!
Sorry for the delay

**Pull request merged**
