### PR TITLE
Support for Herschend Parks (Dollywood + Silver Dollar City)

### PR DESCRIPTION
**Pull request by rambleraptor**
#83 

Wild Adventures doesn't seem to have support for wait times. The base class should make it super easy to add support for future Herschend Parks as long as they continue to use the same endpoint format.

### CODE REVIEW

**Comment by cubehouse** [comment]
This looks great, can we also add park opening times before integrating? This will keep it in-line with the other supported parks :)

**Comment by rambleraptor** [comment]
I just added in Silver Dollar City opening times. I can look at Dollywood's later on. Turns out both of them use different non-standard APIs.

**Comment by rambleraptor** [comment]
That was actually a lot easier than I thought it would be. Opening times added!

**Comment by cubehouse** [comment]
Sorry for the delay getting back to you on this!

I've made a few adjustments, mostly in bfba7c30.

Mainly sorting out the context of "this". If you need to maintain this through an anonymous function, you need to either bind your "function" using }.bind(this) - or you can use the new shorthand , () => {} which maintains the this context (I've done the latter in this case).

Also, you need to use the back-tick (`) if you want variables within strings to be parsed using the ${} syntax.

Now published in 4.6.14!
Many thanks!

**Comment by rambleraptor** [comment]
Awesome, thanks a lot! I don't ever write Javascript, so I'll keep that in mind for the future. The `this` keyword always seems to trip me up because of context issues.

**Pull request merged**
