### PR TITLE
[~] Update Europa Park api

### PR DESCRIPTION
**Pull request by BenediktCleff**
Bump Europa Park api to lastest version

### CODE REVIEW

**Comment by cubehouse** [comment]
I can approve this later this evening hopefully.

There is a change in here to do with languages too? I fear the .value will be accessed on an undefined value if the find doesn't return anything, which would crash the NodeJS process.

**Comment by BenediktCleff** [comment]
Good point. I will check for a fallback

**Comment by BenediktCleff** [comment]
Added  a check for undefined.

**Comment by cubehouse** [comment]
Thanks for this! Pushed live in 4.7.16.

Sorry it too a little longer to get to this than I said.

**Pull request merged**
