### PR TITLE
Universal Studios Japan

### PR DESCRIPTION
**Pull request by rambleraptor**
Really quick attempt at getting USJ wait times.

Couple issues I'm seeing:

1. I don't have an API to get park open times from (#78 didn't include one. I'll try to fiddle with the app to see if one exists but that probably won't happen for a while)
2. When the park is closed, it just returns { 'status': 2 }, so there's no list of rides to access. Right now, I'm just having the script throw an error.
3. All the names are in Japanese. Not sure if/how you want to handle that.

### CODE REVIEW

**Comment by cubehouse** [comment]
It's annoying when parks don't return rides when they're closed! Best thing would probably be to cache a list of rides to fallback to, and if the cache is empty, have a hard-coded (euch, but unavoidable) list of rides. Sometimes there are other APIs available for getting map data, directions, or something else which you can use to extract the ride list. Might be worth a look if possible.

I'm fine with ride names in Japanese if there is no English translation available. I try and keep everything English if the option is there, but it's often unavoidable.

**Comment by rambleraptor** [comment]
Added in the translations + a cache of rides. I'll try to figure out ride opening times, but parsing HTML isn't really in my Javascript skill set

**Comment by cubehouse** [comment]
I've checked in a file with rides and opening times, which I want to give a bit more testing tonight (when the park is open) before adding to the library.

**Comment by cubehouse** [comment]
Added with 8407bf3a055bb48255ca2b8bb3c722dbaee9f9b4
Will be pushed to npm with 5.1.5

**Pull request closed without merging**
